EasyEstate/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse_lazy
from common.forms import PasswordResetFormWithPlaceholder
from common.forms import PasswordSetFormWithPlaceholder, AuthenticationFormWithPlaceholder
from django.contrib.sitemaps.views import index
from django.contrib.sitemaps.views import sitemap

# from zinnia.sitemaps import AuthorSitemap
# from zinnia.sitemaps import CategorySitemap
# from zinnia.sitemaps import EntrySitemap
# from zinnia.sitemaps import TagSitemap


# blog_urls = ([
#     url(r'^', include('zinnia.urls.capabilities')),
#     url(r'^search/', include('zinnia.urls.search')),
#     url(r'^sitemap/', include('zinnia.urls.sitemap')),
#     url(r'^trackback/', include('zinnia.urls.trackback')),
#     url(r'^blog/tags/', include('zinnia.urls.tags')),
#     url(r'^blog/feeds/', include('zinnia.urls.feeds')),
#     url(r'^blog/random/', include('zinnia.urls.random')),
#     url(r'^blog/authors/', include('zinnia.urls.authors')),
#     url(r'^blog/categories/', include('zinnia.urls.categories')),
#     url(r'^blog/comments/', include('zinnia.urls.comments')),
#     url(r'^blog/entries/', include('zinnia.urls.entries')),
#     url(r'^blog/archives/', include('zinnia.urls.archives')),
#     url(r'^blog/shortlink', include('zinnia.urls.shortlink')),
#     url(r'^blog/quick_entry/', include('zinnia.urls.quick_entry'))
# ])

# sitemaps = {
#     'tags': TagSitemap,
#     'blog': EntrySitemap,
#     'authors': AuthorSitemap,
#     'categories': CategorySitemap
# }

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^accounts/', include(('registration.backends.default.urls', 'django_registration'), namespace='accounts')),
    # url(r'^account/login/$', auth_views.LoginView, {'authentication_form': AuthenticationFormWithPlaceholder}, name='login'),
    url(r'^account/logout/$', auth_views.LogoutView, {'next_page': reverse_lazy('index')}, name='logout'),
    url(r'^accounts/register/complete/$', TemplateView.as_view(template_name='registration/registration_complete.html'),name='registration_complete'),
    url(r'^accounts/activate/complete/$', TemplateView.as_view(template_name='registration/activation_complete.html'),name='registration_activation_complete'),
    url(r'^account/password-reset/$', auth_views.PasswordResetView, {'password_reset_form': PasswordResetFormWithPlaceholder}, name='password_reset'),
    url(r'^account/password-rest/done/$', auth_views.PasswordResetDoneView, name='password_reset_done'),
    url(r'^account/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView, {'set_password_form': PasswordSetFormWithPlaceholder}, name='password_reset_confirm'),
    url(r'^account/reset/done/$', auth_views.PasswordResetCompleteView, name='password_reset_complete'),
    # url(r'^', include(blog_urls)),
    # url(r'^blog/', include('zinnia.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^agents/', include(('Agents.urls', 'Agents'), namespace='agents')),
    #url(r'^blog/', include('Blog.urls', namespace='blog')),
    url(r'^message/', include(('message.urls', 'message'), namespace='message')),
    url(r'^controlpanel/', include(('ControlPanel.urls', 'COntrolPanel'), namespace='control')),
    url(r'^customers/', include(('Customers.urls', 'Customer'), namespace='customers')),
    url(r'^faq/', include(('FAQ.urls', 'FAQ'), namespace='faq')),
    url(r'^order/', include(('Order.urls', 'Order'), namespace='order')),
    url(r'^payments/', include(('Payments.urls', 'Payments'), namespace='payments')),
    url(r'^promotion/', include(('Promotion.urls', 'Promotion'), namespace='promotion')),
    url(r'^service/', include(('Services.urls', 'Services'), namespace='service')),
    url(r'^socialmedia/', include(('SocialMedia.urls', 'SocialMedia'), namespace='social')),
    url(r'^common/', include(('common.urls', 'common'), namespace='common')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += [
#     url(r'^sitemap.xml$', index, {'sitemaps': sitemaps}),
#     url(r'^sitemap-(?P<section>.+)\.xml$', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
# ]

apps/Services/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views


urlpatterns = [
    url(r'^acfe131(?P<pk>\d+)6acbtds/manage-service/$', views.ManageService.as_view(), name='manage_service'),
    url(r'^acfe131(?P<user_id>\d+)6acbtds/create-profile/$', views.provider, name='create_profile'),
    url(r'^acfe131(?P<requester_id>\d+)6acbtds/custom-request/$', views.requestservice, name='request_service'),
    url(r'^acfe131(?P<request_id>\d+)6acbtds/request-interest/$', views.requestinterests, name='request_interest'),
    url(r'^acfe131(?P<pk>\d+)6acbtds/my-requests/$', views.MyRequest.as_view(), name='my_requests'),
    url(r'^acfe131(?P<pk>\d+)6acbtds/edit-requests/$', views.RequestServicesEdit.as_view(), name='edit_requests'),
    url(r'^(?P<request_id>\d+)/confirm_delete/$', views.deleterequest, name='delete'),
    url(r'^(?P<provider_id>\d+)/build-profile/$', views.buildprofile, name='build_profile'),
    url(r'^(?P<id>\d+)/approve-request/$', views.approverequest, name='approve_request'),
    url(r'^result/$', views.findprovider, name='search'),
]

apps/common/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    url(r'^accounts/direct/$', views.direct, name='direct'),
    url(r'^acbtds34(?P<user_id>\d+)6acbtds/create-profile/$', views.profile, name='create_profile'),
    url(r'^acfe131(?P<pk>\d+)6acbtds/profile/$', views.UserProfile.as_view(), name='profile'),
    url(r'^acfe131(?P<profile_id>\d+)6acbtds/jobs/$', views.availablejobs, name='available_jobs'),
    url(r'^accounts/common/$', views.common, name='common'),
    url(r'^acfe135(?P<pk>\d+)6acbtds/welcome/$', views.ProfileSetUp.as_view(), name='initial'),
    url(r'^acfe135(?P<pk>\d+)9acbtds/services-professionals/$', views.ListServiceType.as_view(), name='service'),
    url(r'^acfe131(?P<pk>\d+)6acbtds/provider-detail/$', views.ServiceProviderDetail.as_view(), name='provider_detail'),
    url(r'^send-msg/$', views.send_msg, name='send_msg'),
    url(r'^about/$', views.about, name='about_us'),
]

apps/message/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^art5e3(?P<user_id>\d+)e4th5/message-provider/$', views.messageprovider, name='message_provider'),
    url(r'^ars5e3(?P<pk>\d+)e4th5/messages/$', views.MessageProviderDetail.as_view(), name='messages'),
    url(r'^ars5e3(?P<user_id>\d+)e4th5/chart/$', views.chat, name='chart'),
    url(r'^(?P<sender_id>\d+)/suggestion/$', views.mail_suggestion, name='suggestion'),
    url(r'^(?P<property_id>\d+)/email-seller/$', views.emailseller, name='create'),
]

apps/message/models.py
from django.db import models
from Services.models import Providers
from common.models import Profile
from Agents.models import PropertyUpload

class MessageProvider(models.Model):
    receiver = models.ForeignKey(Providers, on_delete=models.CASCADE)
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE)
    sender_name = models.CharField(max_length=200)
    message_subject = models.CharField(max_length=255)
    message = models.TextField()
    phone = models.CharField(max_length=11)
    date_created = models.DateTimeField(editable=False, auto_now_add=True)
    read = models.BooleanField(default=False)

    def __str__(self):
        return self.sender.user.username

class Chart(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    message = models.TextField()
    date_create = models.DateTimeField(auto_now_add=True)

class EmailSeller(models.Model):
    property = models.ForeignKey(PropertyUpload, on_delete=models.CASCADE)
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE)
    your_name = models.CharField(max_length=255)
    email_address = models.EmailField()
    contact_no = models.CharField(max_length=11)
    message = models.TextField()
    subject = models.CharField(max_length=255)

    def __str__(self):
        return self.your_name

apps/message/forms.py
from django import forms
from .models import MessageProvider, EmailSeller

class MessageProviderForm(forms.ModelForm):
    class Meta:
        model = MessageProvider
        exclude = ('receiver', 'sender', 'read', )
        widgets = {
            'message_subject': forms.TextInput(attrs={'class': 'form-control','placeholder':'Your Email'}),
            'sender_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your Name'}),
            'message': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Your Message'}),
        }

    def save(self,user,sender):
        message = super(MessageProviderForm, self).save(commit=False)
        message.receiver = user
        message.sender = sender
        message.save()

class EmailSellerForm(forms.ModelForm):
    class Meta:
        model = EmailSeller
        exclude = ('property', 'receiver', )

    def save(self, property, receiver):
        email = super(EmailSellerForm, self).save(commit=False)
        email.property = property
        email.receiver = receiver
        email.save()

apps/message/views.py
from django.shortcuts import render, get_object_or_404, redirect
from common.models import Profile
from django.views import generic
from django.core.validators import validate_email
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import MessageProviderForm, EmailSellerForm
from Services.models import Providers
from django.http import JsonResponse
from Agents.models import PropertyUpload, Category
from .models import MessageProvider, EmailSeller,  Chart
import datetime
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse

@login_required
def messageprovider(request, user_id):
    profile = get_object_or_404(Profile, pk=user_id)
    sender = get_object_or_404(Profile, pk=request.user.profile.pk)
    receiver = get_object_or_404(Providers, provider_id=profile)
    full_name = request.POST.get('full_name')
    subject = request.POST.get('email_subject')
    message = request.POST.get('message')
    phone = request.POST.get('phone')
    data = {'sender':sender, 'receiver':receiver, 'sender_name':full_name,'message':message, 'message_subject':subject, 'phone':phone}
    f = MessageProviderForm(data)
    if f.is_valid() and f.clean():
        email = MessageProvider.objects.create(sender=sender, receiver=receiver, sender_name=full_name,message=message,
                                message_subject=subject, phone=phone, date_created=datetime.datetime.now, read='False')
        send_mail(subject, "Sender's Details: {}, {}. \n {}".format(sender.user.email, phone, message), 'EasyEstate.com.ng <noreply@easyestate.com.ng>', [receiver.provider.user.email])
    else:
        messages.warning(request, 'There is an error in your submission {}'.format(f.errors))
        return redirect('common:provider_detail', receiver.pk)
    messages.success(request, 'Email delivered successfully to {}. Thanks {} for your interest'.format(receiver.full_name.capitalize(), full_name))
    return redirect('common:provider_detail', receiver.pk)

class MessageProviderDetail(generic.DetailView):
    model = Profile
    template_name = 'message/messages.html'

def chat(request, user_id):
    user = get_object_or_404(Profile, pk=user_id)
    chart = Chart.objects.all()
    return render(request, 'message/chat.html', {'chart':chart})

def post(request):
    if request.method =="POST":
        msg = request.POST.get("msgbox", None)
        c = Chart(user=request.user.profile, message=msg)
        if msg != "":
            c.save()
        return JsonResponse({'msg':msg, 'user':c.user.username})

def emailseller(request, property_id):
    property = get_object_or_404(PropertyUpload, pk=property_id)
    full_name = request.POST.get('full_name')
    subject = request.POST.get('email_subject')
    message = request.POST.get('message')
    from_email = request.POST.get('email_address')
    phone = request.POST.get('phone')
    data = {'property':property, 'receiver':property.created_by_id, 'your_name':full_name, 'email_address':from_email,
            'message':message, 'subject':subject, 'contact_no':phone}
    f = EmailSellerForm(data)
    if f.is_valid() and f.clean():
        email = EmailSeller.objects.create(property=property, receiver=property.created_by, your_name=full_name,
        email_address=from_email, message=message, subject=subject, contact_no=phone)
        send_mail(subject, "Sender's Details: {}, {}. \n {}".format(from_email, phone, message), 'EasyEstate.com.ng <noreply@easyestate.com.ng>', [property.created_by.user.email])
    else:
        messages.warning(request, 'There is an error in your submission')
        return redirect('agents:property_detail', property.pk)
    messages.success(request, "Email delivered successfully to {}. Thanks {} for your interest. Seller's Contact: {}".format(property.created_by.user.username.capitalize(), full_name, property.created_by.phone_number))
    return redirect('agents:property_detail', property.pk)

def mail_suggestion(request, sender_id):
    sender = get_object_or_404(Profile, pk=sender_id)
    if request.method == 'POST':
        level = request.POST.get('level')
        suggestion = request.POST.get('suggestion')
        category = request.POST.get('category')
        message = "Sender's Details: {}, {}.\n Category:{}.\n Level: {}.\n {}".format(sender.user.email, sender.phone_number, category, level, suggestion)
        send_mail("Feature Suggestions", message, 'EasyEstate.com.ng <noreply@easyestate.com.ng>', ['mailing.easyestate@gmail.com', 'chisomike11@gmail.com'])
    return redirect('common:profile', sender.pk)

apps/message/templates/message/chat.html
{% extends 'index.html' %}
{% load static %}
{% block loader %}
{% endblock %}
{% block search %}
{% endblock %}
{% block hero %}
{% endblock %}
{% block content %}
      <div class="small-breadcrumb">
         <div class="container">
            <div class=" breadcrumb-link">
               <ul>
               	  <li><a href="index.html">Home</a></li>
                  <li><a href="index.html">Profile</a></li>
                  <li><a class="active" href="index.html">Inbox</a></li>
               </ul>
            </div>
         </div>
      </div>
      <!-- Small Breadcrumb -->
      <!-- =-=-=-=-=-=-= Transparent Breadcrumb End =-=-=-=-=-=-= -->
      <!-- =-=-=-=-=-=-= Main Content Area =-=-=-=-=-=-= -->
      <div class="main-content-area clearfix">
         <!-- =-=-=-=-=-=-= Latest Ads =-=-=-=-=-=-= -->
         <!-- COURSE CONCERN -->
         <section class="section-padding gray">
            <div class="container">
                  <div class="row">
                   <div class="message-body">
                     <div class="col-md-4 col-sm-5 col-xs-12">
                        <div class="message-inbox">
                           <div class="message-header">
                              <h4>Inbox</h4>
                           </div>
                           <ul class="message-history">
                              <!-- LIST ITEM -->
                              <li class="message-grid">
                                 <a href="#">
                                    <div class="image">
                                       <img src="images/users/1.jpg" alt="">
                                    </div>
                                    <div class="user-name">
                                       <div class="author">
                                          <span>John Doe</span><div class="user-status"></div>
                                       </div>
                                       <p>Xperia Z5 For Sale</p>
                                       <div class="time">
                                           <span>7 days ago</span>
                                       </div>
                                    </div>
                                 </a>
                              </li>
                              <!-- END / LIST ITEM -->
                              <!-- LIST ITEM -->
                              <li class="message-grid">
                                 <a href="#">
                                    <div class="image">
                                       <img src="images/users/2.jpg" alt="">
                                    </div>
                                    <div class="user-name">
                                       <div class="author">
                                          <span>Alex Curt</span><div class="user-status"></div>
                                       </div>
                                       <p>BMW Car For Sale</p>
                                       <div class="time">
                                          <span>2 days ago</span>
                                       </div>
                                    </div>
                                 </a>
                              </li>
                              <!-- END / LIST ITEM -->

                              <!-- LIST ITEM -->
                              <li class="message-grid">
                                 <a href="#">
                                    <div class="image">
                                       <img src="images/users/3.jpg" alt="">
                                    </div>
                                    <div class="user-name">
                                       <div class="author">
                                          <span>Sonu Monu</span><div class="user-status"></div>
                                       </div>
                                       <p>Xperia z5 for sale</p>
                                       <div class="time">
                                           <span>1 days ago</span>
                                       </div>
                                    </div>
                                 </a>
                              </li>
                              <!-- END / LIST ITEM -->
                              <!-- LIST ITEM -->
                              <li class="active">
                                 <a href="#">
                                    <div class="image">
                                       <img src="images/users/4.jpg" alt="">
                                    </div>
                                    <div class="user-name">
                                       <div class="author">
                                          <span>Arslan Tariq</span><div class="user-status"></div>
                                       </div>
                                       <p>HHonda Civic 2017 Sports</p>
                                       <div class="time">
                                          <span>3 days ago</span>
                                       </div>
                                    </div>
                                 </a>
                              </li>
                              <!-- END / LIST ITEM -->
                              <!-- LIST ITEM -->
                              <li class="message-grid">
                                 <a href="#">
                                    <div class="image">
                                       <img src="images/users/5.jpg" alt="">
                                    </div>
                                    <div class="user-name">
                                       <div class="author">
                                          <span>Alexa Grey</span><div class="user-status"></div>
                                       </div>
                                       <p>Pet For Sale</p>
                                       <div class="time">
                                          <span>1 days ago</span>
                                       </div>

                                    </div>
                                 </a>
                              </li>
                              <!-- END / LIST ITEM -->
                              <!-- LIST ITEM -->
                              <li>
                                 <a href="#">
                                    <div class="image">
                                       <img src="images/users/6.jpg" alt="">
                                    </div>
                                    <div class="user-name">
                                       <div class="author">
                                          <span>Humayun</span><div class="user-status"></div>
                                       </div>
                                       <p>Lcd for sale</p>
                                       <div class="time">
                                          <span>5 days ago</span>
                                       </div>
                                    </div>
                                 </a>
                              </li>
                              <!-- END / LIST ITEM -->
                           </ul>
                        </div>
                     </div>
                     <div class="col-md-8 clearfix col-sm-5 col-xs-12 message-content">
                        <div class="message-details">
                           <div class="author" id="charts">
                              <div class="image">
                                 <img src="{{ user.profile.photo.url }}" alt="">
                              </div>
                              <span class="author-name">{{ user.username }}</span>
                              <em>5 days ago</em>
                           </div>
                           <h2>Sony Xperia Z5 For Sale</h2>
                           <ul class="messages" id="msg-list">
                              {% for obj in chart %}
                                  {% if obj.user in request.user.profile %}
                                      <li class="friend-message clearfix">
                                          <figure class="profile-picture">
                                              <img src="images/users/1.jpg" class="img-circle" alt="Profile Pic">
                                          </figure>
                                          <div class="message">
                                              {{ obj.message }}
                                              <div class="time"><i class="fa fa-clock-o"></i>{{ obj.date_created|date:"a" }}</div>
                                          </div>
                                      </li>
                                  {% else %}
                                      <li class="my-message clearfix">
                                         <figure class="profile-picture">
                                            <img src="{{ obj.photo.url }}" class="img-circle" alt="Profile Pic">
                                         </figure>
                                         <div class="message">
                                            {{ obj.message }}
                                            <div class="time"><i class="fa fa-clock-o"></i>{{ obj.date_created|date:"a" }}</div>
                                         </div>
                                      </li>
                                  {% endif %}
                              {% empty %}
                                  <li class="my-message clearfix">
                                      <figure class="profile-picture">
                                            <img src="{{ user.profile.photo.url }}" class="img-circle" alt="Profile Pic">
                                         </figure>
                                      <div class="message">
                                          No Message
                                      </div>
                                  </li>
                              {% endfor %}
                           <script>
                               var chartlist = document.getElementByID('charts');
                               chartlist.scrollTop = chartlist.scrollRight
                           </script>
                           <script src="{% static 'js/easyestate.js' %}"></script>
                           </ul>
                           <div class="chat-form ">
                              <form role="form" class="form-inline" method="post" id="chartform">
                                 {% csrf_token %}
                                 <div class="form-group">
                                    -msg<input style="width: 100%" placeholder="Type a message here..." class="form-control" type="text" id="chat-msg" name="chat-msg">
                                 </div>
                                 <button class="btn btn-theme" type="submit">Send</button>
                              </form>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </section>
         <!-- END / COURSE CONCERN -->
         <!-- =-=-=-=-=-=-= Ads Archives End =-=-=-=-=-=-= -->
         <!-- =-=-=-=-=-=-= FOOTER =-=-=-=-=-=-= -->
         <!-- =-=-=-=-=-=-= FOOTER END =-=-=-=-=-=-= -->
      </div>
{% endblock %}

apps/message/templates/message/messages.html
{% extends 'index.html' %}
{% load static %}
{% block loader %}
{% endblock %}
{% block search %}
{% endblock %}
{% block hero %}
{% endblock %}
{% block content %}
<div class="page-header-area">
         <div class="container">
            <div class="row">
               <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="header-page">
                     <h1>Create Your Request</h1>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- Small Breadcrumb -->
<div class="small-breadcrumb">
         <div class="container">
            <div class=" breadcrumb-link">
               <ul>
                  <li><a href="{% url 'index' %}">Home</a></li>
                  <li><a href="{% url 'common:profile' user.profile.pk %}">Profile</a></li>
                  <li><a href="{% url 'service:manage_service' user.profile.pk %}">Manage Service</a></li>
                  <li><a class="active" href="">Custom Service Request</a></li>
               </ul>
            </div>
         </div>
      </div>
<div class="main-content-area clearfix">
    <section class="section-padding error-page pattern-bg ">
        <div class="container">
            <div class="col-lg-12 connectedSortable">
                <ul class="nav nav-tabs" role="tablist">
                      <li class="col-lg-4 col-xs-6 active"><a href="#tab1" role="tab" data-toggle="tab">All Messages</a></li>
                      <li class="col-lg-4 col-xs-6"><a href="#tab2" role="tab" data-toggle="tab">Unread Messages</a></li>
                      <li class="col-lg-4 col-xs-6"><a href="#tab3" role="tab" data-toggle="tab">Sent Messages</a></li>
                </ul>
        <!-- TAB CONTENT -->
            <div class="tab-content">
                <div class="active tab-pane fade in" id="tab1">
                   {% for messageprovider in object.messageprovider_set.all %}
                    <a href="">
                        <div class="user-name">
                            <div class="author">
                                <img src="{{ messageprovider.sender.photo.url }}" alt="" style="height:3em; width:3em;" class="img-circle"><span>{{ messageprovider.sender_name }}</span><div class="user-status"></div>
                            </div>
                            <p style="text-indent:3em;">{{ messageprovider.message }}</p>
                            <div class="time">
                                <p style="text-indent:3em;">sent:{{ messageprovider.date_created|date:'D d M Y' }}</p>
                            </div>
                        </div>
                    </a>
                   {% endfor %}
                  </div>
                <div class="tab-pane fade" id="tab2">
                    {% for messageprovider in object.messageprovider_set.all %}
                    {% if messageprovider.read == False %}
                    <a href="#">
                        <div class="user-name">
                            <div class="author">
                                <img src="{{ messageprovider.sender.photo.url }}" alt="" style="height:3em; width:3em;" class="img-circle"><span>{{ messageprovider.sender_name }}</span><div class="user-status"></div>
                            </div>
                            <p style="text-indent:3em;">{{ messageprovider.message }}</p>
                            <div class="time">
                                <p style="text-indent:3em;">sent:{{ messageprovider.date_created|date:'D d M Y' }}</p>
                            </div>
                        </div>
                    </a>
                    {% endif %}
                    {% endfor %}
                  </div>
                <div class="tab-pane fade" id="tab3">
                    {% for messageprovider in object.messageprovider_set.all %}
                    <a href="#">
                        <div class="user-name">
                            <div class="author">
                                <img src="{{ messageprovider.sender.photo.url }}" alt="" style="height:3em; width:3em;" class="img-circle"><span>{{ messageprovider.sender_name }}</span><div class="user-status"></div>
                            </div>
                            <p style="text-indent:3em;">{{ messageprovider.message }}</p>
                            <div class="time">
                                <p style="text-indent:3em;">sent:{{ messageprovider.date_created|date:'D d M Y' }}</p>
                            </div>
                        </div>
                    </a>
                    {% endfor %}
                  </div>
            </div>
    </div>
    </div>
</section>
</div>

{% endblock %}