EasyEstate/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse_lazy
from common.forms import PasswordResetFormWithPlaceholder
from common.forms import PasswordSetFormWithPlaceholder, AuthenticationFormWithPlaceholder
from django.contrib.sitemaps.views import index
from django.contrib.sitemaps.views import sitemap

# from zinnia.sitemaps import AuthorSitemap
# from zinnia.sitemaps import CategorySitemap
# from zinnia.sitemaps import EntrySitemap
# from zinnia.sitemaps import TagSitemap


# blog_urls = ([
#     url(r'^', include('zinnia.urls.capabilities')),
#     url(r'^search/', include('zinnia.urls.search')),
#     url(r'^sitemap/', include('zinnia.urls.sitemap')),
#     url(r'^trackback/', include('zinnia.urls.trackback')),
#     url(r'^blog/tags/', include('zinnia.urls.tags')),
#     url(r'^blog/feeds/', include('zinnia.urls.feeds')),
#     url(r'^blog/random/', include('zinnia.urls.random')),
#     url(r'^blog/authors/', include('zinnia.urls.authors')),
#     url(r'^blog/categories/', include('zinnia.urls.categories')),
#     url(r'^blog/comments/', include('zinnia.urls.comments')),
#     url(r'^blog/entries/', include('zinnia.urls.entries')),
#     url(r'^blog/archives/', include('zinnia.urls.archives')),
#     url(r'^blog/shortlink', include('zinnia.urls.shortlink')),
#     url(r'^blog/quick_entry/', include('zinnia.urls.quick_entry'))
# ])

# sitemaps = {
#     'tags': TagSitemap,
#     'blog': EntrySitemap,
#     'authors': AuthorSitemap,
#     'categories': CategorySitemap
# }

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^accounts/', include(('registration.backends.default.urls', 'django_registration'), namespace='accounts')),
    # url(r'^account/login/$', auth_views.LoginView, {'authentication_form': AuthenticationFormWithPlaceholder}, name='login'),
    url(r'^account/logout/$', auth_views.LogoutView, {'next_page': reverse_lazy('index')}, name='logout'),
    url(r'^accounts/register/complete/$', TemplateView.as_view(template_name='registration/registration_complete.html'),name='registration_complete'),
    url(r'^accounts/activate/complete/$', TemplateView.as_view(template_name='registration/activation_complete.html'),name='registration_activation_complete'),
    url(r'^account/password-reset/$', auth_views.PasswordResetView, {'password_reset_form': PasswordResetFormWithPlaceholder}, name='password_reset'),
    url(r'^account/password-rest/done/$', auth_views.PasswordResetDoneView, name='password_reset_done'),
    url(r'^account/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView, {'set_password_form': PasswordSetFormWithPlaceholder}, name='password_reset_confirm'),
    url(r'^account/reset/done/$', auth_views.PasswordResetCompleteView, name='password_reset_complete'),
    # url(r'^', include(blog_urls)),
    # url(r'^blog/', include('zinnia.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^agents/', include(('Agents.urls', 'Agents'), namespace='agents')),
    #url(r'^blog/', include('Blog.urls', namespace='blog')),
    url(r'^message/', include(('message.urls', 'message'), namespace='message')),
    url(r'^controlpanel/', include(('ControlPanel.urls', 'COntrolPanel'), namespace='control')),
    url(r'^customers/', include(('Customers.urls', 'Customer'), namespace='customers')),
    url(r'^faq/', include(('FAQ.urls', 'FAQ'), namespace='faq')),
    url(r'^order/', include(('Order.urls', 'Order'), namespace='order')),
    url(r'^payments/', include(('Payments.urls', 'Payments'), namespace='payments')),
    url(r'^promotion/', include(('Promotion.urls', 'Promotion'), namespace='promotion')),
    url(r'^service/', include(('Services.urls', 'Services'), namespace='service')),
    url(r'^socialmedia/', include(('SocialMedia.urls', 'SocialMedia'), namespace='social')),
    url(r'^common/', include(('common.urls', 'common'), namespace='common')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += [
#     url(r'^sitemap.xml$', index, {'sitemaps': sitemaps}),
#     url(r'^sitemap-(?P<section>.+)\.xml$', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
# ]

apps/Services/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views


urlpatterns = [
    url(r'^acfe131(?P<pk>\d+)6acbtds/manage-service/$', views.ManageService.as_view(), name='manage_service'),
    url(r'^acfe131(?P<user_id>\d+)6acbtds/create-profile/$', views.provider, name='create_profile'),
    url(r'^acfe131(?P<requester_id>\d+)6acbtds/custom-request/$', views.requestservice, name='request_service'),
    url(r'^acfe131(?P<request_id>\d+)6acbtds/request-interest/$', views.requestinterests, name='request_interest'),
    url(r'^acfe131(?P<pk>\d+)6acbtds/my-requests/$', views.MyRequest.as_view(), name='my_requests'),
    url(r'^acfe131(?P<pk>\d+)6acbtds/edit-requests/$', views.RequestServicesEdit.as_view(), name='edit_requests'),
    url(r'^(?P<request_id>\d+)/confirm_delete/$', views.deleterequest, name='delete'),
    url(r'^(?P<provider_id>\d+)/build-profile/$', views.buildprofile, name='build_profile'),
    url(r'^(?P<id>\d+)/approve-request/$', views.approverequest, name='approve_request'),
    url(r'^result/$', views.findprovider, name='search'),
]

apps/common/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    url(r'^accounts/direct/$', views.direct, name='direct'),
    url(r'^acbtds34(?P<user_id>\d+)6acbtds/create-profile/$', views.profile, name='create_profile'),
    url(r'^acfe131(?P<pk>\d+)6acbtds/profile/$', views.UserProfile.as_view(), name='profile'),
    url(r'^acfe131(?P<profile_id>\d+)6acbtds/jobs/$', views.availablejobs, name='available_jobs'),
    url(r'^accounts/common/$', views.common, name='common'),
    url(r'^acfe135(?P<pk>\d+)6acbtds/welcome/$', views.ProfileSetUp.as_view(), name='initial'),
    url(r'^acfe135(?P<pk>\d+)9acbtds/services-professionals/$', views.ListServiceType.as_view(), name='service'),
    url(r'^acfe131(?P<pk>\d+)6acbtds/provider-detail/$', views.ServiceProviderDetail.as_view(), name='provider_detail'),
    url(r'^send-msg/$', views.send_msg, name='send_msg'),
    url(r'^about/$', views.about, name='about_us'),
]

apps/message/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^art5e3(?P<user_id>\d+)e4th5/message-provider/$', views.messageprovider, name='message_provider'),
    url(r'^ars5e3(?P<pk>\d+)e4th5/messages/$', views.MessageProviderDetail.as_view(), name='messages'),
    url(r'^ars5e3(?P<user_id>\d+)e4th5/chart/$', views.chat, name='chart'),
    url(r'^(?P<sender_id>\d+)/suggestion/$', views.mail_suggestion, name='suggestion'),
    url(r'^(?P<property_id>\d+)/email-seller/$', views.emailseller, name='create'),
]

apps/Services/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.views import generic
from state.models import LGA, State
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from common.models import Profile
from django.db.models import Q
from django.core.mail import send_mail
import datetime
from django.urls import reverse
from .forms import ProviderForm, RequestServiceForm, RequestInterestsForm, RequestServicesEditForm, ProfileBuildForm
from .models import Providers, RequestServices, RequestInterest, ServiceType
from django.contrib import messages


# function to create a service profile
def provider(request, user_id):
    pro = get_object_or_404(Profile, pk=user_id)
    if request.method == "POST":
        form = ProviderForm(request.POST)
        if form.is_valid():
            form.save(pro)
            messages.success(request, 'Profile creation successful')
            return redirect('service:manage_service', pro.pk)
    else:
        form = ProviderForm()
    return render(request, 'services/create_profile.html', {'form': form})

# class that handles users service section (Manage Service)
class ManageService(generic.DetailView):
    model = Profile
    template_name = 'services/manage_service.html'

    # fetch's the service the user renders, if any
    def get_context_data(self, **kwargs):
        pk = Profile.objects.get(pk=self.kwargs['pk'])
        provider = Providers.objects.all().filter(provider_id=pk)
        req = RequestServices.objects.all().filter(requester_id=pk)
        g = RequestInterest.objects.filter(Q(interested_person_id=provider) & Q(status='Granted'))
        context = super(ManageService, self).get_context_data(**kwargs)
        if provider:
            pro = Providers.objects.select_related('service_provided').get(provider_id=pk)
            type = ServiceType.objects.filter(service=pro.service_provided)
            jobs = RequestServices.objects.filter(type_of_service=type)
            p = pro.service_provided
            context['provider'] = p
            context['jobs'] = jobs.count()
        if g:
            context['offered'] = g.count()
        context['requester'] = req.count()
        return context

def requestservice(request, requester_id):
    requester = get_object_or_404(Profile, pk=requester_id)
    if request.method == 'POST':
        form = RequestServiceForm(request.POST)
        if form.is_valid():
            form.save(requester)
            messages.success(request, 'Request successfully created')
            return redirect('service:my_requests', requester.pk)
    else:
        form = RequestServiceForm()
    return render(request, 'services/custom_request.html', {'form': form})

def requestinterests(request, request_id):
    req = get_object_or_404(RequestServices, pk=request_id)
    provider = request.user.profile.providers
    if request.method == 'POST':
        form = RequestInterestsForm(request.POST)
        if form.is_valid():
            form.save(req, provider)
            messages.success(request, 'Offer Sent')
            return redirect('service:my_requests', request.user.profile.pk)
    else:
        form = RequestInterestsForm()
    return render(request, 'services/send_proposal.html', {'form':form})

class MyRequest(generic.DetailView):
    model = Profile
    template_name = 'services/custom_requests.html'
    def get_context_data(self,  **kwargs):
        pk = Profile.objects.get(pk=self.kwargs['pk'])
        provider = Providers.objects.all().filter(provider_id=pk)
        sent_request = RequestInterest.objects.all().filter(interested_person_id=provider)
        req = RequestServices.objects.all().filter(requester_id=pk)
        g = RequestInterest.objects.filter(Q(interested_person_id=provider) & Q(status='Granted'))
        d = datetime.datetime.now()
        due = RequestInterest.objects.filter(due_date__lte=d).update(status='Completed')
        context = super(MyRequest, self).get_context_data(**kwargs)
        if sent_request:
            context['jobs'] = sent_request.count()
        if req:
            context['requester'] = req.count()
        if g:
            context['offered'] = g.count()
        return context

def deleterequest(request, request_id):
    obj = get_object_or_404(RequestServices, pk=request_id)
    if request.method == "POST":
        parent_url = obj.requester.get_absolute_url()
        obj.delete()
        messages.success(request, "Item deleted")
        return HttpResponseRedirect(parent_url)
    return render(request, 'services/request_services_confirm_delete.html', {'object':obj})

class RequestServicesEdit(generic.UpdateView):
    model = RequestServices
    form_class = RequestServicesEditForm
    template_name = 'services/request_services_edit.html'

    def get_success_url(self):
        return reverse('service:my_requests', kwargs={'pk': self.request.user.profile.pk})

def buildprofile(request, provider_id):
    profile = Profile.objects.get(pk=provider_id)
    provider = Providers.objects.get(provider_id=profile)
    if request.method == "POST":
        form = ProfileBuildForm(request.POST, request.FILES)
        if form.is_valid():
            form.save(provider)
            messages.success(request, 'Added successfully')
            return redirect('service:manage_service', profile.pk)
    else:
        form = ProfileBuildForm()
    return render(request, 'services/build_profile.html', {'form': form})


def approverequest(request, id):
    p = RequestInterest.objects.get(pk=id)
    req = RequestServices.objects.get(pk=p.request_id)
    t = Profile.objects.get(pk=req.requester_id)
    i = Providers.objects.get(pk=p.interested_person_id)
    date = datetime.timedelta(days=p.duration)
    time = datetime.datetime.now() + date
    interest = RequestInterest.objects.filter(pk=id).update(status='Granted')
    due_date = RequestInterest.objects.filter(pk=id).update(due_date=time)
    email = send_mail('Request Approval', "your offer '{}' has been granted".format(p.my_offer),
                      'EasyEstate.com.ng < noreply @ easyestate.com.ng>',
                      [i.provider.user.email])
    messages.success(request, 'You have granted {} the job. \n Job Due Date is: {}'.format(i.full_name, p.due_date))
    return redirect('service:my_requests', t.pk)

def findprovider(request):
    page = request.GET.get('page', 1)
    where_in_state = request.GET.get('lga')
    state = request.GET.get('state')
    service_type = request.GET.get('service_type')
    p = LGA.objects.get(name__icontains=where_in_state)
    s = State.objects.get(name__icontains=state)
    r = Providers.objects.filter(service_provided=service_type)
    t = Profile.objects.filter(Q(lga=p) & Q(state=s))
    results = Providers.objects.filter(Q(provider=t) | Q(service_provided=service_type))
    paginator = Paginator(results, 3)
    try:
        sult = paginator.page(page)
    except PageNotAnInteger:
        sult = paginator.page(1)
    except EmptyPage:
        sult = paginator.page(paginator.num_pages)
    return render(request, 'services/result.html', {'sult':sult})

apps/Services/templates/services/manage_service.html
{% extends 'index.html' %}
{% load static %}
{% block loader %}
{% endblock %}
{% block search %}
{% endblock %}
{% block hero %}
{% endblock %}
{% block content %}
      <div class="small-breadcrumb">
         <div class="container">
            <div class=" breadcrumb-link">
               <ul>
                  <li><a href="{% url 'index' %}">Home</a></li>
                  <li><a href="{% url 'common:profile' object.pk %}">Profile</a></li>
                  <li><a class="active" href="{% url 'service:manage_service' object.pk %}">Manage Service</a></li>
               </ul>
            </div>
         </div>
      </div>
      <!-- Small Breadcrumb -->
      <!-- =-=-=-=-=-=-= Main Content Area =-=-=-=-=-=-= -->
      <div class="main-content-area clearfix">
         <!-- =-=-=-=-=-=-= Latest Ads =-=-=-=-=-=-= -->
         <section class="section-padding gray">
            <!-- Main Container -->
            <div class="container">
               <!-- Row -->
               <div class="row">
                   {% if messages %}
                   {% for message in messages %}
                        <div class="alert alert-success alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <p>{{ message }}</p>
                        </div>
                   {% endfor %}
                   {% endif %}
                  <!-- Middle Content Area -->
                  <div class="col-md-4 col-sm-12 col-xs-12 leftbar-stick blog-sidebar">
                     <!-- Sidebar Widgets -->
                     <div class="user-profile">
                        <a href="{% url 'common:profile' object.pk %}" style="height:50px;">
                            {% if user.profile.photo %}
                            <img src="{{ user.profile.photo.url }}" alt="">
                            {% elif 'M' in user.profile.gender %}
                                <img src="{% static 'images/male-avatar.jpg' %}" alt="">
                            {% else %}
                                <img src="{% static 'images/female-avatar.png' %}" alt="" style="">
                            {% endif %}
                        </a>
                        <div class="profile-detail">
                           <h6>{{ user.username }}</h6>
                           <ul class="contact-details">
                              <li>
                                 <i class="fa fa-map-marker"></i> {{ object.address }}
                              </li>
                              <li>
                                 <i class="fa fa-envelope"></i>{{ user.email }}
                              </li>
                              <li>
                                 <i class="fa fa-phone"></i> {{ object.phone_number }}
                              </li>
                               <li>
                                 <i class="fa fa-cc"></i> {{ provider }}
                              </li>
                           </ul>
                        </div>
                        <ul>
                           <li class="active"><a href="{% url 'service:manage_service' user.profile.pk %}">Manage Service </a></li>
                           <li><a href="{% url 'common:profile' object.pk %}">Profile {% for provider in object.provider_set.all %} {{ provider.service_provided }}{% endfor %} </a></li>
                           <li><a href="{% url 'service:create_profile' object.pk %}">Create Service Profile </a></li>
                           {% if object.providers %}<li><a href="{% url 'service:build_profile' object.pk %}">Build Profile </a></li>{% endif %}
                           {% if object.providers %}<li><a href="#">Promote Profile </a></li>{% endif %}
                            <li><a href="#">Find a Service </a></li>
                           <li><a href="{% url 'service:request_service' object.pk %}">Custom Service Request</a></li>
                           <li><a href="{% url 'service:my_requests' object.pk %}">Custom Requests & Orders <span class="badge">{{ requester }}</span> </a></li>
                           {% if object.providers %}<li><a href="{% url 'common:available_jobs' object.pk %}">Available Jobs <span class="badge">{{ jobs }}</span></a></li>{% endif %}
                           <li><a href="">Transaction History </a></li>
                           <li ><a href="{% url 'message:messages' object.pk %}">Messages <span class="badge"></span></a></li>
                           <li><a href="/account/logout">Logout</a></li>
                        </ul>
                     </div>
                     <!-- Categories -->
                     <div class="widget">
                        <div class="widget-heading">
                           <h4 class="panel-title"><a>Change Your Plan</a></h4>
                        </div>
                        <div class="widget-content">
                           <select class=" form-control">
                              <option label="Select Option"></option>
                              <option value="0">Free</option>
                              <option value="1">Premium</option>
                              <option value="2">Featured</option>
                           </select>
                        </div>
                     </div>
                  </div>
                  <div class="col-md-8 col-sm-12 col-xs-12">
                     <!-- Row -->
                     <div class="row">
                        <!-- Sorting Filters -->
                        <div class="col-md-12 col-xs-12 col-sm-12 col-lg-12">
                           <!-- Sorting Filters Breadcrumb -->
                           <!-- Sorting Filters Breadcrumb End -->
                        </div>
                        <!-- Sorting Filters End-->
                        <div class="clearfix"></div>
                        <!-- Ads Archive -->
                        <div class="posts-masonry">
                           <div class="col-md-12 col-xs-12 col-sm-12 user-archives">
                              <!-- Ads Listing -->
                               <div class="carousel-row">
                                 <div class="slide-row">
                                    <div class="carousel slide slide-carousel" id="carousel-1" data-ride="carousel">
                                       <!-- Indicators -->
                                       <ol class="carousel-indicators">
                                          <li data-target="#carousel-1" data-slide-to="0" class="active"></li>
                                          <li data-target="#carousel-1" data-slide-to="1"></li>
                                          <li data-target="#carousel-1" data-slide-to="2"></li>
                                       </ol>

                                       <!-- Wrapper for slides -->
                                       <div class="carousel-inner">
                                          <div class="item active">
                                             <img src="{% static 'images/slider1.jpg' %}" alt="Image" style="width:100%;">
                                          </div>
                                          <div class="item">
                                             <img src="{% static 'images/slider2.jpg' %}" alt="Image" style="width:100%;">
                                          </div>
                                          <div class="item">
                                             <img src="{% static 'images/slider3.jpg' %}" alt="Image" style="width:100%;">
                                          </div>
                                       </div>
                                    </div>
                                    <div class="slide-content" style="padding-left:10px; padding-top:10px;">
                                       <h3>Information Page</h3>
                                       <p>
                                          You will get all the necessary information from EasyEstate, as they come up here.
                                       </p>
                                    </div>
                                    <div class="slide-footer">
                                          <span class="pull-right buttons">
                                              <button class="btn btn-sm btn-primary"><i class="fa fa-info"></i> Know more</button>
                                          </span>
                                    </div>
                                 </div>
                              </div>
                               <div class="row">
                                    <div class="clearfix"></div>
                                    <div class="tab-content">
                                        <div class="posts-masonry active tab-pane fade in" id="tab1">
                                            <div class="col-md-12 col-xs-12 col-sm-12 user-archives">
                                              <div class="ads-list-archive" style="padding-left:10%; padding-top:10px;">
                                                  <h3 style="position:relative; left:20%">How Service work on EasyEstate</h3>
                                                  <p style="position:relative; left:20%">On <em>EasyEstate</em> you can either <em><b>Buy</b></em> or <em><b>Sell</b></em> house related services</p>
                                                  <h4><b>How To Sell Service(s) </b></h4>
                                                  <ul>
                                                      <li>&nbsp;&nbsp;&nbsp;&nbsp;<b>&#42</b> After you have signup on EasyEstate</li>
                                                      <li>&nbsp;&nbsp;&nbsp;&nbsp;<b>&#42</b> You will have create a service profile by click <em><b><a href="{% url 'service:create_profile' object.pk %}">Create Service Profile</a></b></em></li>
                                                      <li>&nbsp;&nbsp;&nbsp;&nbsp;<b>&#42</b> After creating your profile, specifying the kind of service your provide, <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; prospective client will then be able to find you when your service is sort on EasyEstate</li>
                                                  </ul>
                                                  <br>
                                                  <p> That easy right!</p>
                                                  <p><em><b>Note</b></em>: Be sure to provide the right information that will give to a competitive advantage.</p>
                                                  <h4><b>How to buy Service </b></h4>
                                                  <ul>
                                                      <li>&nbsp;&nbsp;&nbsp;&nbsp;<b>&#42</b> Search for the Service you seek for </li>
                                                      <li>&nbsp;&nbsp;&nbsp;&nbsp;<b>&#42</b> Contact the Provider (seller) either by email or buy phone call</li>
                                                      <li>&nbsp;&nbsp;&nbsp;&nbsp;<b>&#42</b> Communicate with the seller</li>
                                                      <li>&nbsp;&nbsp;&nbsp;&nbsp;<b>&#42</b> Pay after the job has been done</li>
                                                  </ul>
                                                  <p> That easy right!</p>
                                                  <p><em><b>Note</b></em>: Ensure to meet in a place that is deemed safe if need be, for the safety of both parties.</p>
                                                  <h4><b>How to find service providers (sellers) </b></h4>
                                                  <ul>
                                                      <li>&nbsp;&nbsp;&nbsp;&nbsp;<b>&#42</b> You can create a custom request i.e a detail of what you are in need of, and allow sellers contact you based on your request and you decide who to pick, by click on <b><a href="{% url 'service:request_service' object.pk %}">Custom Service Request</a></b></li>
                                                      <li>&nbsp;&nbsp;&nbsp;&nbsp;<b>&#42</b> You can also find sellers by clicking on <em><b><a href="#">Find a service</a></b></em> from Manage Service Page</li>
                                                      <li>&nbsp;&nbsp;&nbsp;&nbsp;<b>&#42</b> You can as well find seller from the service categories on the <em><b><a href="{% url 'index' %}">Home Page</a></b></em></li>
                                                  </ul>
                                                  &nbsp;&nbsp;&nbsp;&nbsp;
                                              </div>
                                            </div>
                                        </div>
                                    </div>
                               <div class="clearfix"></div>
                           </div>
                        </div>
                        <!-- Ads Archive End -->
                        <div class="clearfix"></div>

                        <!-- Pagination -->
                        <!-- Pagination End -->
                     </div>
                     <!-- Row End -->
                  </div>
                  <!-- Middle Content Area  End -->
               </div>
               <!-- Row End -->
            </div>
            </div>
            <!-- Main Container End -->
         </section>
      </div>
{% endblock %}

apps/Services/templates/services/send_proposal.html
{% extends 'index.html' %}
{% load static %}
{% block loader %}
{% endblock %}
{% block search %}
{% endblock %}
{% block hero %}
{% endblock %}
{% block content %}
<div class="page-header-area">
         <div class="container">
            <div class="row">
                {% if messages %}
                   {% for message in messages %}
                        <div class="alert alert-success alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <p>{{ message }}</p>
                        </div>
                   {% endfor %}
                {% endif %}
               <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="header-page">
                     <h1>Create Your Request</h1>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- Small Breadcrumb -->
<div class="small-breadcrumb">
         <div class="container">
            <div class=" breadcrumb-link">
               <ul>
                  <li><a href="{% url 'index' %}">Home</a></li>
                  <li><a href="{% url 'common:profile' user.profile.pk %}">Profile</a></li>
                  <li><a href="{% url 'service:manage_service' user.profile.pk %}">Manage Service</a></li>
                  <li><a href="">Available Jobs </a></li>
                  <li><a class="active" href="">Bid Job </a></li>
               </ul>
            </div>
         </div>
      </div>
      <div class="main-content-area clearfix">
         <!-- =-=-=-=-=-=-= Latest Ads =-=-=-=-=-=-= -->
         <section class="section-padding error-page pattern-bg ">
            <!-- Main Container -->
            <div class="container">
               <!-- Row -->
               <div class="row">
                   {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-success alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <p>{{ message }}</p>
                        </div>
                        {% endfor %}
                   {% endif %}
                  <!-- Middle Content Area -->
                  <div class="col-md-7 col-sm-12 col-xs-12">
                     <!--  Form -->
                     <div class="form-grid">
                        <form method="post" action="">
                            {% csrf_token %}
                            <div class="form-group">
                                 {{ form.my_offer.errors }}
                                 {{ form.my_offer.label }}
                                {{ form.my_offer }}
                            </div>
                            <div class="form-group">
                                 {{ form.price_offer.errors }}
                                 {{ form.price_offer.label }}
                                {{ form.price_offer }}
                            </div>
                            <div class="form-group">
                                 {{ form.duration.errors }}
                                 {{ form.duration.label }}
                                {{ form.duration}}
                            </div>
                            <input type="submit" value="Send">
                        </form>
                     </div>
                     <!-- Form -->
                  </div>

                  <!-- Middle Content Area  End -->
               </div>
               <!-- Row End -->
            </div>
         </section>
      </div>
{% endblock %}