EasyEstate/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse_lazy
from common.forms import PasswordResetFormWithPlaceholder
from common.forms import PasswordSetFormWithPlaceholder, AuthenticationFormWithPlaceholder
from django.contrib.sitemaps.views import index
from django.contrib.sitemaps.views import sitemap

# from zinnia.sitemaps import AuthorSitemap
# from zinnia.sitemaps import CategorySitemap
# from zinnia.sitemaps import EntrySitemap
# from zinnia.sitemaps import TagSitemap


# blog_urls = ([
#     url(r'^', include('zinnia.urls.capabilities')),
#     url(r'^search/', include('zinnia.urls.search')),
#     url(r'^sitemap/', include('zinnia.urls.sitemap')),
#     url(r'^trackback/', include('zinnia.urls.trackback')),
#     url(r'^blog/tags/', include('zinnia.urls.tags')),
#     url(r'^blog/feeds/', include('zinnia.urls.feeds')),
#     url(r'^blog/random/', include('zinnia.urls.random')),
#     url(r'^blog/authors/', include('zinnia.urls.authors')),
#     url(r'^blog/categories/', include('zinnia.urls.categories')),
#     url(r'^blog/comments/', include('zinnia.urls.comments')),
#     url(r'^blog/entries/', include('zinnia.urls.entries')),
#     url(r'^blog/archives/', include('zinnia.urls.archives')),
#     url(r'^blog/shortlink', include('zinnia.urls.shortlink')),
#     url(r'^blog/quick_entry/', include('zinnia.urls.quick_entry'))
# ])

# sitemaps = {
#     'tags': TagSitemap,
#     'blog': EntrySitemap,
#     'authors': AuthorSitemap,
#     'categories': CategorySitemap
# }

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^accounts/', include(('registration.backends.default.urls', 'django_registration'), namespace='accounts')),
    # url(r'^account/login/$', auth_views.LoginView, {'authentication_form': AuthenticationFormWithPlaceholder}, name='login'),
    url(r'^account/logout/$', auth_views.LogoutView, {'next_page': reverse_lazy('index')}, name='logout'),
    url(r'^accounts/register/complete/$', TemplateView.as_view(template_name='registration/registration_complete.html'),name='registration_complete'),
    url(r'^accounts/activate/complete/$', TemplateView.as_view(template_name='registration/activation_complete.html'),name='registration_activation_complete'),
    url(r'^account/password-reset/$', auth_views.PasswordResetView, {'password_reset_form': PasswordResetFormWithPlaceholder}, name='password_reset'),
    url(r'^account/password-rest/done/$', auth_views.PasswordResetDoneView, name='password_reset_done'),
    url(r'^account/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView, {'set_password_form': PasswordSetFormWithPlaceholder}, name='password_reset_confirm'),
    url(r'^account/reset/done/$', auth_views.PasswordResetCompleteView, name='password_reset_complete'),
    # url(r'^', include(blog_urls)),
    # url(r'^blog/', include('zinnia.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^agents/', include(('Agents.urls', 'Agents'), namespace='agents')),
    #url(r'^blog/', include('Blog.urls', namespace='blog')),
    url(r'^message/', include(('message.urls', 'message'), namespace='message')),
    url(r'^controlpanel/', include(('ControlPanel.urls', 'COntrolPanel'), namespace='control')),
    url(r'^customers/', include(('Customers.urls', 'Customer'), namespace='customers')),
    url(r'^faq/', include(('FAQ.urls', 'FAQ'), namespace='faq')),
    url(r'^order/', include(('Order.urls', 'Order'), namespace='order')),
    url(r'^payments/', include(('Payments.urls', 'Payments'), namespace='payments')),
    url(r'^promotion/', include(('Promotion.urls', 'Promotion'), namespace='promotion')),
    url(r'^service/', include(('Services.urls', 'Services'), namespace='service')),
    url(r'^socialmedia/', include(('SocialMedia.urls', 'SocialMedia'), namespace='social')),
    url(r'^common/', include(('common.urls', 'common'), namespace='common')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += [
#     url(r'^sitemap.xml$', index, {'sitemaps': sitemaps}),
#     url(r'^sitemap-(?P<section>.+)\.xml$', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
# ]

apps/Agents/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views


urlpatterns = [
    url(r'^absre4g64(?P<user_id>\d+)4t5f/property-upload/$', views.propertyupload, name='property_upload'),
    url(r'^ausre4g64(?P<pk>\d+)4t5f/properties/$', views.UserProperties.as_view(), name='user_properties'),
    url(r'^(?P<request_id>\d+)/confirm_property_delete/$', views.deleteproperty, name='delete'),
    url(r'^acfe131(?P<pk>\d+)6acbtds/edit-property/$', views.PropertyUpdate.as_view(), name='edit_property'),
    url(r'^(?P<property_id>\d+)/promote-property/$', views.promoteproperty, name='promote_property'),
    url(r'^lga-search/$', views.ajax_lga_search, name='lga-search'),
    url(r'^state-search/$', views.ajax_state_search, name='state-search'),
    url(r'^search-result/$', views.findproperty, name='search'),
    url(r'^(?P<pk>\d+)/property-detail/$', views.PropertyDetail.as_view(), name='property_detail'),
    url(r'^ausre4g64(?P<pk>\d+)4t5f/ads/$', views.UserAds.as_view(), name='user_ads'),
]

apps/common/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    url(r'^accounts/direct/$', views.direct, name='direct'),
    url(r'^acbtds34(?P<user_id>\d+)6acbtds/create-profile/$', views.profile, name='create_profile'),
    url(r'^acfe131(?P<pk>\d+)6acbtds/profile/$', views.UserProfile.as_view(), name='profile'),
    url(r'^acfe131(?P<profile_id>\d+)6acbtds/jobs/$', views.availablejobs, name='available_jobs'),
    url(r'^accounts/common/$', views.common, name='common'),
    url(r'^acfe135(?P<pk>\d+)6acbtds/welcome/$', views.ProfileSetUp.as_view(), name='initial'),
    url(r'^acfe135(?P<pk>\d+)9acbtds/services-professionals/$', views.ListServiceType.as_view(), name='service'),
    url(r'^acfe131(?P<pk>\d+)6acbtds/provider-detail/$', views.ServiceProviderDetail.as_view(), name='provider_detail'),
    url(r'^send-msg/$', views.send_msg, name='send_msg'),
    url(r'^about/$', views.about, name='about_us'),
]

apps/Agents/models.py
from django.db import models
from common.models import Profile
import datetime
from django.urls import reverse
from state.models import State, LGA
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import User


SEX_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female'),
)

HOW = (
    ('FF', 'From a Friend'),
    ('SM', 'Social Media'),
    ('OF', 'From our Orientation Meeting'),
    ('FG', 'From Google'),
    ('FE', 'From Email'),
)

STATUS = (
    ('Running', 'Running'),
    ('Expired', 'Expired'),
)


class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.name

class Available(models.Model):
    property_type = models.CharField(max_length=50, default='Rent')

    def __str__(self):
        return self.property_type

class PriceRange(models.Model):
    price = models.DecimalField(max_digits=15, decimal_places=0)


class PropertyUpload(models.Model):
    STATUS = (
        ('Running', 'Running'),
        ('Expired', 'Expired'),
        ('Pending', 'Pending'),
        ('Rejected', 'Rejected'),
        ('Approved', 'Approved'),
    )

    created_by = models.ForeignKey(Profile, on_delete=models.CASCADE)
    property_type = models.ForeignKey(Category, null=True, on_delete=models.CASCADE)
    availability_type = models.ForeignKey(Available, null=True, on_delete=models.CASCADE)
    main_view = models.ImageField(upload_to='Agents')
    right_view = models.ImageField(upload_to='Agents', blank=True)
    back_view = models.ImageField(upload_to='Agents', blank=True)
    left_view = models.ImageField(upload_to='Agents', blank=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=15, decimal_places=0)
    number_of_room = models.CharField(max_length=10, blank=True)
    number_of_toilet = models.CharField(max_length=10, blank=True)
    number_of_baths = models.CharField(max_length=10, blank=True)
    property_state = models.ForeignKey(State, on_delete=models.CASCADE)
    property_lga = models.ForeignKey(LGA, on_delete=models.CASCADE)
    water = models.CharField(max_length=100, blank=True)
    power = models.CharField(max_length=100, blank=True)
    date_created = models.DateField(editable=False, auto_now_add=True)
    date_expire = models.DateTimeField()
    is_expired = models.BooleanField()
    status = models.CharField(max_length=50, choices=STATUS, default='Pending')
    running = models.CharField(max_length=10, choices=STATUS, default='Running')

    class Meta:
        ordering = ['-date_created']

    def save(self):
        date = datetime.timedelta(days=30)
        if not self.id:
            self.date_expire = datetime.datetime.now() + date
        super(PropertyUpload, self).save()

    def __str__(self):
        return self.property_type.name

    def get_absolute_url(self):
        return reverse('agents:user_properties', kwargs={'pk': self.created_by.pk})

apps/Agents/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect, HttpResponse
from .forms import PropertyUploadForm, PropertyUpdateForm
from Payments.models import FundAccount, PromoteProperty
from Payments.forms import PromotePropertyForm
from .models import PropertyUpload, Category
from common.models import Profile
from state.models import LGA, State
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.core.serializers.json import DjangoJSONEncoder
import json
import datetime
from django.db.models import Q
from django.views import generic
from django.contrib import messages
from django.urls import reverse

def propertyupload(request, user_id):
    created_by = get_object_or_404(Profile, pk=user_id)
    if request.method == "POST":
        form = PropertyUploadForm(request.POST,request.FILES)
        if form.is_valid():
            form.save(created_by)
            messages.success(request, 'Property uploaded successfully')
            send_mail('Approval Request', 'You have a property awaiting approval', 'EasyEstate.com.ng <noreply@easyestate.com.ng>', ['chisomike11@gmail.com'])
            return redirect('common:profile', created_by.pk)
    else:
        form = PropertyUploadForm()
    return render(request, 'agents/property_upload.html', {'form':form})



class UserProperties(generic.DetailView):
    model = Profile
    template_name = 'agents/user_properties.html'

    def get_context_data(self, **kwargs):
        pk = Profile.objects.get(pk=self.kwargs['pk'])
        property = PropertyUpload.objects.filter(created_by_id=pk)
        context = super(UserProperties, self).get_context_data(**kwargs)
        for e in property:
            d = datetime.datetime.now()
            #t = e.date_created
            status = PropertyUpload.objects.filter(running='Running', date_expire__lte=d).update(running='Expired')
            #status2 = PropertyUpload.objects.filter(Q(running='Expired') & Q(date_created=t)).update(running='Running')
            context['status'] = status
            return context

class UserAds(generic.DetailView):
    model = Profile
    template_name = 'agents/user_ads.html'

    def get_context_data(self, **kwargs):
        pk = Profile.objects.get(pk=self.kwargs['pk'])
        person = PropertyUpload.objects.filter(created_by_id=pk)
        context = super(UserAds, self).get_context_data(**kwargs)
        d = datetime.datetime.now()
        status = PromoteProperty.objects.filter(Q(promoter_id=pk) & Q(expires__gte=d))
        context['running'] = status.count()
        return context


def deleteproperty(request, request_id):
    obj = get_object_or_404(PropertyUpload, pk=request_id)
    if request.method == "POST":
        parent_url = obj.created_by.get_absolute_url()
        obj.delete()
        messages.success(request, "Item deleted")
        return HttpResponseRedirect(parent_url)
    return render(request, 'agents/confirm_property_delete.html', {'object':obj})

class PropertyUpdate(generic.UpdateView):
    model = PropertyUpload
    form_class = PropertyUpdateForm
    template_name = 'agents/property_update_form.html'

    def get_success_url(self):
        return reverse('agents:user_properties', kwargs={'pk': self.request.user.profile.pk})

def promoteproperty(request, property_id):
    property = get_object_or_404(PropertyUpload, pk=property_id)
    promoter = property.created_by_id
    profile = get_object_or_404(Profile, pk=promoter)
    promoter_fund = FundAccount.objects.filter(payee_id=promoter)
    if request.method=='POST':
        form = PromotePropertyForm(request.POST)
        for available_fund in promoter_fund:
            if form.is_valid() and form.cleaned_data['visibility_point'].transaction_cost < available_fund.new_balance:
                available_fund.new_balance = available_fund.new_balance - form.cleaned_data['visibility_point'].transaction_cost
                FundAccount.objects.filter(payee_id=profile).update(new_balance=available_fund.new_balance)
                form.save(property, profile)
                messages.success(request, 'Ad promotion started')
                redirect('agents:user_properties', profile.pk)
            else:
                messages.success(request, 'You are low on fund')
    else:
        form = PromotePropertyForm()
    return render(request, 'agents/promote_property.html', {'form':form})

def findproperty(request, ):
    if request.method == 'GET':
        where_in_state = request.GET.get('lga')
        state = request.GET.get('state')
        price_max = request.GET.get('price_max')
        property_type = request.GET.get('property_type')
        p = LGA.objects.filter(name__icontains=where_in_state)
        s = State.objects.get(name__icontains=state)
        t = Category.objects.get(name__icontains=property_type)
        result = PropertyUpload.objects.filter(Q(status='Approved'), Q(property_type=t) | Q(property_lga=p) | Q(property_state=s) | Q(price__lte=price_max))
        return render(request, 'agents/result.html', {'result': result})
    else:
        return render(request, 'agents/result.html', {})

def ajax_lga_search(request):
    if request.is_ajax():
        q = request.GET.get('term', '')
        nigerian_state = request.GET.get('nigerian_state', '')
        state =State.objects.filter(name__icontains=nigerian_state)
        lgas = LGA.objects.filter(state=state, name__icontains=q)
        results = []
        for pl in lgas:
            lgas_json = {}
            lgas_json['id'] = pl.id
            lgas_json['label'] = pl.name
            lgas_json['value'] = pl.name
            results.append(lgas_json)
        data = json.dumps(list(results), cls=DjangoJSONEncoder)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

def ajax_state_search(request):
    if request.is_ajax():
        q = request.GET.get('term', '')
        states = State.objects.filter(name__icontains=q)
        results = []
        for pl in states:
            states_json = {}
            states_json['id'] = pl.id
            states_json['label'] = pl.name
            states_json['value'] = pl.name
            results.append(states_json)
        data = json.dumps(list(results), cls=DjangoJSONEncoder)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

class PropertyDetail(generic.DetailView):
    model = PropertyUpload
    template_name = 'agents/property_detail.html'

apps/Agents/templates/agents/confirm_property_delete.html
{% extends 'index.html' %}
{% load static %}
{% block loader %}
{% endblock %}
{% block menu %}
{% endblock menu %}
{% block search %}
{% endblock %}
{% block hero %}
{% endblock %}
{% block content %}
<section class="comming-soon-grid">
         <div class="container">
            <div class="row">
               <div class="col-xs-12 comming-soon">
                  <div class="theme-logo">
                     <a href="index.html"><img src="images/logo.png" alt=""></a>
                  </div>
                  <div class="count-down">
                     <div id="clock"></div>
                  </div>
                  <div>
                      <h3>Confirm Delete</h3>
                     </p>
                     <form action="" method="post">
                         {% csrf_token%}
                            <p>Are your sure you want to delete <em><b>"{{ object.property_type }}"</b></em></p>
                            <input type="submit" value="Confirm" class="btn btn-success">
                            <a href="{{ object.get_absolute_url }}" class="btn btn-warning">Cancel</a>
                     </form>
                  </div>
               </div>
            </div>
         </div>
      </section>
{% endblock %}

apps/Agents/templates/agents/promote_property.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for message in messages %}
<div class="alert alert-success">
    <p>{{ message }}</p>
</div>
{% endfor %}
<form method="post" action="" >
	{% csrf_token %}
	{{ form.as_p }}
	<input type=submit value="start">
</form>
</body>
</html>

apps/Agents/templates/agents/user_ads.html
{% extends 'index.html' %}
{% load static %}
{% block loader %}
{% endblock %}
{% block search %}
{% endblock %}
{% block hero %}
{% endblock %}
{% block content %}
      <div class="small-breadcrumb">
         <div class="container">
            <div class=" breadcrumb-link">
               <ul>
                  <li><a href="{% url 'index' %}">Home</a></li>
                  <li><a href="{% url 'common:profile' user.profile.pk %}">Profile</a></li>
                  <li><a class="active" href="#">My Ads </a></li>
               </ul>
            </div>
         </div>
      </div>
      <!-- Small Breadcrumb -->
      <!-- =-=-=-=-=-=-= Main Content Area =-=-=-=-=-=-= -->
      <div class="main-content-area clearfix">
         <!-- =-=-=-=-=-=-= Latest Ads =-=-=-=-=-=-= -->
         <section class="section-padding gray">
            <!-- Main Container -->
            <div class="container">
               <!-- Row -->
               <div class="row">
                  <!-- Middle Content Area -->
                  <div class="col-md-4 col-sm-12 col-xs-12 leftbar-stick blog-sidebar">
                     <!-- Sidebar Widgets -->
                     <div class="user-profile">
                        <a href="profile.html"><img src="images/users/9.jpg" alt=""></a>
                        <div class="profile-detail">
                           <h6>{{ user.username }}</h6>
                           <ul class="contact-details">
                              <li>
                                 <i class="fa fa-map-marker"></i> {{ object.address }}
                              </li>
                              <li>
                                 <i class="fa fa-envelope"></i>{{ user.email }}
                              </li>
                              <li>
                                 <i class="fa fa-phone"></i> {{ object.phone_number }}
                              </li>
                           </ul>
                        </div>
                        <ul>
                           <li ><a href="{% url 'common:profile' object.pk %}">Profile</a></li>
                           <li  class="active"><a href="{% url 'agents:property_upload' object.pk %}">Add a Property</a></li>
                           <li><a href="{% url 'agents:user_properties' object.pk %}">My Properties <span class="badge"></span></a></li>
                           <li><a href="">Running Ads</a></li>
                            <li><a href="">My Service</a></li>
                           <li ><a href="">Messages</a></li>
                           <li><a href="/account/logout">Logout</a></li>
                        </ul>
                     </div>
                     <!-- Categories -->
                     <div class="widget">
                        <div class="widget-heading">
                           <h4 class="panel-title"><a>Change Your Plan</a></h4>
                        </div>
                        <div class="widget-content">
                           <select class=" form-control">
                              <option label="Select Option"></option>
                              <option value="0">Free</option>
                              <option value="1">Premium</option>
                              <option value="2">Featured</option>
                           </select>
                        </div>
                     </div>
                  </div>
                  <div class="col-md-8 col-sm-12 col-xs-12">
                     <!-- Row -->
                     <div class="row">
                        <!-- Sorting Filters -->
                        <div class="col-md-12 col-xs-12 col-sm-12 col-lg-12">
                           <!-- Sorting Filters Breadcrumb -->
                           <!-- Sorting Filters Breadcrumb End -->
                        </div>
                        <!-- Sorting Filters End-->
                        <div class="clearfix"></div>
                        <!-- Ads Archive -->
                        <div class="posts-masonry">
                           <div class="col-md-12 col-xs-12 col-sm-12 user-archives">
                               {% for propertyupload in object.propertyupload_set.all %}
                              <!-- Ads Listing -->
                              <div class="ads-list-archive">
                                 <!-- Image Block -->
                                 <div class="col-lg-5 col-md-5 col-sm-5 no-padding">
                                    <!-- Img Block -->
                                    <div class="ad-archive-img ">
                                       <a href="#">
                                      <div class="ribbon expired">{{ propertyupload.running }}</div>
                                       <img src="{{ propertyupload.main_view.url }}" alt="">
                                       </a>
                                       <div class="sold">
                                          <img class="img-responsive" src="{% static 'images/sold.png' %}" alt="">
                                       </div>
                                    </div>
                                    <!-- Img Block -->
                                 </div>
                                 <!-- Ads Listing -->
                                 <div class="clearfix visible-xs-block"></div>
                                 <!-- Content Block -->
                                 <div class="col-lg-7 col-md-7 col-sm-7 no-padding">
                                    <!-- Ad Desc -->
                                    <div class="ad-archive-desc">
                                       <!-- Price -->
                                       <div class="ad-price">N{{ propertyupload.price }}</div>
                                       <!-- Title -->
                                       <h3>{{ propertyupload.number_of_room }} bedroom {{ propertyupload.property_type }}</h3>
                                       <!-- Category -->
                                       <div class="category-title"> <span><a href="#">{{ propertyupload.property_type }}</a></span> </div>
                                       <!-- Short Description -->
                                       <div class="clearfix visible-xs-block"></div>
                                       <p class="hidden-sm">{{ propertyupload.description }}</p>
                                       <!-- Ad Features -->
                                       <ul class="add_info">
                                          <!-- Contact Details -->
                                          <li>
                                             <div class="custom-tooltip tooltip-effect-4">
                                                <span class="tooltip-item"><i class="fa fa-phone"></i></span>
                                                <div class="tooltip-content">
                                                   <h4>Call Timings</h4>
                                                   <strong>Monday to Friday</strong> 09.00 AM - 5.30 PM
                                                   <br>
                                                   <strong>Saturday</strong> 09.00 AM - 5.30 PM
                                                   <br>
                                                   <strong>Sunday</strong> <span class="label label-success">+92-123-4567</span>
                                                </div>
                                             </div>
                                          </li>
                                          <!-- Address -->
                                          <li>
                                             <div class="custom-tooltip tooltip-effect-4">
                                                <span class="tooltip-item"><i class="fa fa-map-marker"></i></span>
                                                <div class="tooltip-content">
                                                   <h4>Address</h4>
                                                  {{ propertyupload.property_lga }} in {{ propertyupload.property_state }}
                                                </div>
                                             </div>
                                          </li>
                                          <!-- Ad Type -->
                                          <li>
                                             <div class="custom-tooltip tooltip-effect-4">
                                                <span class="tooltip-item"><i class="fa fa-cog"></i></span>
                                                <div class="tooltip-content">
                                                   <strong>Condition</strong> <span class="label label-danger">Used</span>
                                                </div>
                                             </div>
                                          </li>
                                          <!-- Ad Type -->
                                          <li>
                                             <div class="custom-tooltip tooltip-effect-4">
                                                <span class="tooltip-item"><i class="fa fa-check-square-o"></i></span>
                                                <div class="tooltip-content">
                                                   <strong>Warrinty</strong> <span class="label label-danger">No </span>
                                                </div>
                                             </div>
                                          </li>
                                       </ul>
                                       <!-- Ad History -->
                                       <div class="clearfix archive-history">
                                          <div class="last-updated">Created: {{ propertyupload.date_created }} <br> Expires: {{ propertyupload.date_expire }}</div>

                                          <div class="ad-meta">
                                             <a class="btn btn-success" href="{% url 'agents:edit_property' propertyupload.pk %}"><i class="fa fa-pencil"></i> Edit</a>
                                             <a class="btn btn-danger" href="{% url 'agents:delete' propertyupload.pk %}"><i class="fa fa-times"></i> Delete</a>
                                              <a class="btn btn-default" href="{% url 'agents:promote_property' propertyupload.pk %}"><i class="fa fa-plus"></i> Promote</a>
                                          </div>
                                       </div>
                                    </div>
                                    <!-- Ad Desc End -->
                                 </div>
                                 <!-- Content Block End -->
                              </div>
                              <!-- Ads Listing -->
                              {% empty %}
                                <h3>You have no Running Property Ad</h3>
                               {% endfor %}
                           </div>
                        </div>
                        <!-- Ads Archive End -->
                        <div class="clearfix"></div>
                        <!-- Pagination -->
                        <div class="col-md-12 col-xs-12 col-sm-12">
                           <ul class="pagination pagination-lg">
                              <li> <a href="#"> <i class="fa fa-chevron-left" aria-hidden="true"></i></a></li>
                              <li> <a href="#">1</a> </li>
                              <li class="active"> <a href="#">2</a> </li>
                              <li> <a href="#">3</a> </li>
                              <li> <a href="#">4</a> </li>
                              <li><a href="#"> <i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
                           </ul>
                        </div>
                        <!-- Pagination End -->
                     </div>
                     <!-- Row End -->
                  </div>
                  <!-- Middle Content Area  End -->
               </div>
               <!-- Row End -->
            </div>
            <!-- Main Container End -->
         </section>
         <!-- =-=-=-=-=-=-= Ads Archives End =-=-=-=-=-=-= -->
         <!-- =-=-=-=-=-=-= FOOTER =-=-=-=-=-=-= -->
         <!-- =-=-=-=-=-=-= FOOTER END =-=-=-=-=-=-= -->
      </div>
{% endblock %}