EasyEstate/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse_lazy
from common.forms import PasswordResetFormWithPlaceholder
from common.forms import PasswordSetFormWithPlaceholder, AuthenticationFormWithPlaceholder
from django.contrib.sitemaps.views import index
from django.contrib.sitemaps.views import sitemap

# from zinnia.sitemaps import AuthorSitemap
# from zinnia.sitemaps import CategorySitemap
# from zinnia.sitemaps import EntrySitemap
# from zinnia.sitemaps import TagSitemap


# blog_urls = ([
#     url(r'^', include('zinnia.urls.capabilities')),
#     url(r'^search/', include('zinnia.urls.search')),
#     url(r'^sitemap/', include('zinnia.urls.sitemap')),
#     url(r'^trackback/', include('zinnia.urls.trackback')),
#     url(r'^blog/tags/', include('zinnia.urls.tags')),
#     url(r'^blog/feeds/', include('zinnia.urls.feeds')),
#     url(r'^blog/random/', include('zinnia.urls.random')),
#     url(r'^blog/authors/', include('zinnia.urls.authors')),
#     url(r'^blog/categories/', include('zinnia.urls.categories')),
#     url(r'^blog/comments/', include('zinnia.urls.comments')),
#     url(r'^blog/entries/', include('zinnia.urls.entries')),
#     url(r'^blog/archives/', include('zinnia.urls.archives')),
#     url(r'^blog/shortlink', include('zinnia.urls.shortlink')),
#     url(r'^blog/quick_entry/', include('zinnia.urls.quick_entry'))
# ])

# sitemaps = {
#     'tags': TagSitemap,
#     'blog': EntrySitemap,
#     'authors': AuthorSitemap,
#     'categories': CategorySitemap
# }

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^accounts/', include(('registration.backends.default.urls', 'django_registration'), namespace='accounts')),
    # url(r'^account/login/$', auth_views.LoginView, {'authentication_form': AuthenticationFormWithPlaceholder}, name='login'),
    url(r'^account/logout/$', auth_views.LogoutView, {'next_page': reverse_lazy('index')}, name='logout'),
    url(r'^accounts/register/complete/$', TemplateView.as_view(template_name='registration/registration_complete.html'),name='registration_complete'),
    url(r'^accounts/activate/complete/$', TemplateView.as_view(template_name='registration/activation_complete.html'),name='registration_activation_complete'),
    url(r'^account/password-reset/$', auth_views.PasswordResetView, {'password_reset_form': PasswordResetFormWithPlaceholder}, name='password_reset'),
    url(r'^account/password-rest/done/$', auth_views.PasswordResetDoneView, name='password_reset_done'),
    url(r'^account/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView, {'set_password_form': PasswordSetFormWithPlaceholder}, name='password_reset_confirm'),
    url(r'^account/reset/done/$', auth_views.PasswordResetCompleteView, name='password_reset_complete'),
    # url(r'^', include(blog_urls)),
    # url(r'^blog/', include('zinnia.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^agents/', include(('Agents.urls', 'Agents'), namespace='agents')),
    #url(r'^blog/', include('Blog.urls', namespace='blog')),
    url(r'^message/', include(('message.urls', 'message'), namespace='message')),
    url(r'^controlpanel/', include(('ControlPanel.urls', 'COntrolPanel'), namespace='control')),
    url(r'^customers/', include(('Customers.urls', 'Customer'), namespace='customers')),
    url(r'^faq/', include(('FAQ.urls', 'FAQ'), namespace='faq')),
    url(r'^order/', include(('Order.urls', 'Order'), namespace='order')),
    url(r'^payments/', include(('Payments.urls', 'Payments'), namespace='payments')),
    url(r'^promotion/', include(('Promotion.urls', 'Promotion'), namespace='promotion')),
    url(r'^service/', include(('Services.urls', 'Services'), namespace='service')),
    url(r'^socialmedia/', include(('SocialMedia.urls', 'SocialMedia'), namespace='social')),
    url(r'^common/', include(('common.urls', 'common'), namespace='common')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += [
#     url(r'^sitemap.xml$', index, {'sitemaps': sitemaps}),
#     url(r'^sitemap-(?P<section>.+)\.xml$', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
# ]

apps/Services/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views


urlpatterns = [
    url(r'^acfe131(?P<pk>\d+)6acbtds/manage-service/$', views.ManageService.as_view(), name='manage_service'),
    url(r'^acfe131(?P<user_id>\d+)6acbtds/create-profile/$', views.provider, name='create_profile'),
    url(r'^acfe131(?P<requester_id>\d+)6acbtds/custom-request/$', views.requestservice, name='request_service'),
    url(r'^acfe131(?P<request_id>\d+)6acbtds/request-interest/$', views.requestinterests, name='request_interest'),
    url(r'^acfe131(?P<pk>\d+)6acbtds/my-requests/$', views.MyRequest.as_view(), name='my_requests'),
    url(r'^acfe131(?P<pk>\d+)6acbtds/edit-requests/$', views.RequestServicesEdit.as_view(), name='edit_requests'),
    url(r'^(?P<request_id>\d+)/confirm_delete/$', views.deleterequest, name='delete'),
    url(r'^(?P<provider_id>\d+)/build-profile/$', views.buildprofile, name='build_profile'),
    url(r'^(?P<id>\d+)/approve-request/$', views.approverequest, name='approve_request'),
    url(r'^result/$', views.findprovider, name='search'),
]

apps/common/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    url(r'^accounts/direct/$', views.direct, name='direct'),
    url(r'^acbtds34(?P<user_id>\d+)6acbtds/create-profile/$', views.profile, name='create_profile'),
    url(r'^acfe131(?P<pk>\d+)6acbtds/profile/$', views.UserProfile.as_view(), name='profile'),
    url(r'^acfe131(?P<profile_id>\d+)6acbtds/jobs/$', views.availablejobs, name='available_jobs'),
    url(r'^accounts/common/$', views.common, name='common'),
    url(r'^acfe135(?P<pk>\d+)6acbtds/welcome/$', views.ProfileSetUp.as_view(), name='initial'),
    url(r'^acfe135(?P<pk>\d+)9acbtds/services-professionals/$', views.ListServiceType.as_view(), name='service'),
    url(r'^acfe131(?P<pk>\d+)6acbtds/provider-detail/$', views.ServiceProviderDetail.as_view(), name='provider_detail'),
    url(r'^send-msg/$', views.send_msg, name='send_msg'),
    url(r'^about/$', views.about, name='about_us'),
]

apps/common/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from state.models import Country, State, LGA
from .validator import validate_phone
from django.urls import reverse

SEX_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female'),
)

I_AM = (
    ('U', 'User'),
    ('A', 'Agent'),
    ('S', 'Service Provider'),
)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='users', blank=True)
    gender = models.CharField(max_length=1, choices=SEX_CHOICES, default='F')
    phone_number = models.CharField(max_length=11, validators=[validate_phone])
    full_name = models.CharField(max_length=200, default="", blank=False)
    address = models.TextField()
    country = models.ForeignKey(Country, models.CASCADE)
    state = models.ForeignKey(State, models.CASCADE)
    lga = models.ForeignKey(LGA, models.CASCADE)
    i_agree = models.BooleanField(default=False)


    class Meta:
        permissions = (
            ('is_a_user', 'Is a User'),
        )

    def __str__(self):
        return self.user.username

    # @models.permalink
    def get_absolute_url(self):
        return reverse('common:profile', (), args=(self.pk, ))

apps/common/forms.py
from django import forms
from .models import Profile
import datetime
from django.contrib.auth.models import User, Permission
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django_registration.forms import RegistrationFormUniqueEmail
from django.forms.widgets import PasswordInput, TextInput, EmailInput
from django.contrib.auth.hashers import make_password

class AccountCreationForm(RegistrationFormUniqueEmail):
    username = forms.CharField(widget=TextInput(attrs={'class': 'form-control','placeholder': 'your username'}))
    email = forms.EmailField(widget=EmailInput(attrs={'class': 'form-control','placeholder':'your email address'}))
    password1 = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control','placeholder':'*******'}))
    password2 = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control', 'placeholder': '*******'}))

class AuthenticationFormWithPlaceholder(AuthenticationForm):
    username = forms.CharField(widget=TextInput(attrs={'class': 'form-control','placeholder': 'Username or Email'}))
    password = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control','placeholder':'Password'}))


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user', )
        widgets = {
            'country': forms.Select(attrs={'class': 'form-control'}),
            'state': forms.Select(attrs={'class': 'form-control'}),
            'lga': forms.Select(attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'full_name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.NumberInput(attrs={'class': 'form-control'}),
            'photo': forms.FileInput(attrs={'class': 'form-control'}),
            'address': forms.Textarea(attrs={'class': 'form-control'}),
            'i_agree': forms.CheckboxInput(attrs={'class': 'form-control', 'required':'True'})

        }

    def save(self, user):
        profile = super(ProfileForm, self).save(commit=False)
        profile.user = user
        profile.save()
        permission = Permission.objects.get(codename='is_a_user')
        user.user_permissions.add(permission)
        profile.save()

class PasswordResetFormWithPlaceholder(PasswordResetForm):
    email = forms.CharField(widget=TextInput(attrs={'class': 'form-control','placeholder': 'Email'}))

class PasswordSetFormWithPlaceholder(SetPasswordForm):
    new_password1 = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control','placeholder': 'New Password'}))
    new_password2 = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control','placeholder': 'Confirm New Password'}))

apps/common/views.py
from django.shortcuts import render, redirect
from .forms import ProfileForm
from django.views import generic
from .models import Profile
from django.contrib.auth.mixins import LoginRequiredMixin
from Agents.models import PropertyUpload, Category, Available
from Services.models import RequestServices, ServiceType, Providers
from Payments.models import FundAccount, PromoteProperty
from django.contrib import messages
from django.contrib.auth.models import User, Permission
from django.shortcuts import get_object_or_404
import datetime
from django.core.mail import send_mail
from django.db.models import Q

def profile(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    print('-------', request.method)
    if request.method =='POST':
        form = ProfileForm(request.POST, request.FILES)
        print('=====2', form.is_valid)
        if form.is_valid():
            form.save(user)
            messages.success(request, 'Profile successfully created')
            return redirect('accounts:auth_login')
    else:
        form = ProfileForm()
        print('=========', request.method, user)
    return render(request, 'common/create_profile.html', {'form':form})

class ProfileSetUp(generic.DetailView):
    model = User
    template_name = 'common/initial_setup.html'


class UserProfile(LoginRequiredMixin, generic.DetailView):
    login_url = '/accounts/login/'
    redirect_field_name = 'login'
    model = Profile
    template_name = 'common/dashboard.html'

    def get_context_data(self, **kwargs):
        pk = Profile.objects.get(pk=self.kwargs['pk'])
        property = PropertyUpload.objects.all().filter(created_by=pk)
        fund_acc = FundAccount.objects.all().filter(payee_id=pk)
        context = super(UserProfile, self).get_context_data(**kwargs)
        d = datetime.datetime.now()
        all_ads = PromoteProperty.objects.filter(promoter_id=pk)
        running_ads = PromoteProperty.objects.filter(Q(promoter_id=pk) & Q(expires__gte=d))
        if fund_acc:
            fund = FundAccount.objects.order_by('fundaccount__id').latest('new_balance')
            context['fund'] = fund
        if all_ads:
            context['all_ads'] = all_ads.count()
        context['count'] = property.count()
        context['running'] = running_ads.count()
        return context

def common(request):
    if request.user.profile:
        return redirect('common:profile', pk=request.user.profile.pk)

def direct(request):
    if request.user.has_perm('common.is_a_user'):
        return redirect('common:common')
    else:
        return redirect('common:initial', pk=request.user.pk)

class AvailableJobs(generic.DetailView):
    model = Profile
    template_name = 'common/available_jobs.html'

def availablejobs(request, profile_id):
    profile = get_object_or_404(Profile, pk=profile_id)
    provider = Providers.objects.get(provider_id=profile_id)
    type = ServiceType.objects.filter(service=provider.service_provided)
    requests = RequestServices.objects.filter(type_of_service=type)
    context_list = {'requests':requests}
    return render(request, 'common/available_jobs.html', context_list)

class ListServiceType(generic.DetailView):
    model = ServiceType
    template_name = 'common/service_professionals.html'

class ServiceProviderDetail(generic.DetailView):
    model = Providers
    template_name = 'common/service_provider_detail.html'


class AuthorUpdate(generic.UpdateView):
    model = Profile
    fields = ['name']
    template_name_suffix = '_update_form'

def send_msg(request):
    name = request.POST.get('name')
    msg = request.POST.get('msg')
    subject = request.POST.get('subject')
    email = request.POST.get('mail')
    data = {'name':name, 'msg':msg, 'subject':subject, 'email':email}
    if data:
        message = "%s: %s via %s" % (name, msg, email)
        send_mail(subject, message, 'EasyEstate.com.ng <noreply@easyestate.com.ng>', ['mailing.accomodo@gmail.com'])
        messages.success(request, 'Message sent')
    return redirect('index')

def about(request):
    return render(request, 'common/about_us.html')

apps/common/templates/common/about_us.html
{% extends 'index.html' %}
{% load static %}
{% block loader %}
{% endblock %}
{% block search %}
{% endblock %}
{% block hero %}
{% endblock %}
{% block content %}
      <div class="page-header-area">
         <div class="container">
            <div class="row">
               <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="header-page">
                     <h1>About Us</h1>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- Small Breadcrumb -->
      <div class="small-breadcrumb">
         <div class="container">
            <div class=" breadcrumb-link">
               <ul>
                  <li><a href="{% url 'index' %}">Home Page</a></li>
                  <li><a href="#">Pages</a></li>
                  <li><a class="active" href="{% url 'common:about_us' %}">About Us</a></li>
               </ul>
            </div>
         </div>
      </div>
      <!-- Small Breadcrumb -->
      <!-- =-=-=-=-=-=-= Transparent Breadcrumb End =-=-=-=-=-=-= -->
      <!-- =-=-=-=-=-=-= Main Content Area =-=-=-=-=-=-= -->
      <div class="main-content-area clearfix">
         <!-- =-=-=-=-=-=-= Latest Ads =-=-=-=-=-=-= -->
         <section class="section-padding pattern_dots">
            <!-- Main Container -->
            <div class="container">
               <!-- Row -->
               <div class="row">
                  <div class="col-lg-6 col-md-6 col-sm-7 col-xs-12">
                     <div class="about-us-content">
                        <div class="heading-panel">
                           <h3 class="main-title text-left">
                              About EasyEstate
                           </h3>
                        </div>
                        <h2></h2>
                        <p>EASYESTATE.COM.NG, a product of Judan technologies, is primarily;</p>
                        <p>An online real estate platform which connects property(lands and housing)owners, agents and brokers to prospective clients willing to buy, lease or rent these properties.</p>
                         <p>An online platform where house maintenance service providers such as Plumbers, Electricians, Painters,
                             Surveyors, Architects, Real Estate Valuers, Carpenters, Interior decorators etc gets connected to clients who need their services.</p>
                         <p>Our goal is to effectively solve the problem of property owners and house maintenance service providers - prospective clients hectic connection involved in the business of real estate, and providing a common marketplace for them using the power of technology</p>
                     </div>
                  </div>
                  <div class="col-lg-6 col-md-6 col-sm-5 col-xs-12">
                     <div class="about-page-featured-image">
                        <a href="{% url 'index' %}"><img src="{% static 'images/easy1.jpg' %}" alt=""></a>
                     </div>
                  </div>
               </div>
               <!-- Row End -->
            </div>
            <!-- Main Container End -->
         </section>
         <!-- =-=-=-=-=-=-= Ads Archives End =-=-=-=-=-=-= -->
         <section class="about-us">
            <div class="container-fluid">
               <div class="row">
                  <div class="col-md-12 no-padding">
                     <!-- service box 3 -->
                     <div class="col-sm-4 col-md-4 col-xs-12 no-padding">
                        <div class="why-us border-box text-center">
                           <h5>Why choose us</h5>
                           <p>Mauris eros tortor, tristique cursus porttitor et, luctus sed urna. Quisque id libero risus. Aliquam accumsan erat id sem placerat tempus.</p>
                        </div>
                     </div>
                     <!-- service box end -->
                     <!-- service box 3 -->
                     <div class="col-sm-4 col-md-4 col-xs-12 no-padding">
                        <div class="why-us border-box text-center">
                           <h5>Our mission</h5>
                           <p>To effectively solve the problem of property owners and house maintenance service providers - prospective clients hectic connection involved in the business of real estate, and providing a common marketplace for them using the power of technology</p>
                        </div>
                        <!-- end featured-item -->
                     </div>
                     <!-- service box end -->
                     <!-- service box 3 -->
                     <div class="col-sm-4 col-md-4 col-xs-12 no-padding">
                        <div class="why-us border-box text-center">
                           <h5>Only creative solutions</h5>
                           <p>Mauris eros tortor, tristique cursus porttitor et, luctus sed urna. Quisque id libero risus. Aliquam accumsan erat id sem placerat tempus.</p>
                        </div>
                        <!-- end featured-item -->
                     </div>
                     <!-- service box end -->
                  </div>
               </div>
            </div>
            <!-- end container -->
         </section>
         <div class="clearfix"></div>
         <!-- =-=-=-=-=-=-= Statistics Counter =-=-=-=-=-=-= -->
         <div class="funfacts custom-padding parallex">
            <div class="container">
               <div class="row">
                  <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                     <div class="icons">
                        <i class="flaticon-home-1"></i>
                     </div>
                     <div class="number"><span>{{ featured|length }}</span>+</div>
                     <h4>Fea<span>tured</span></h4>
                  </div>
                  <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                     <div class="icons">
                        <i class="flaticon-home-2"></i>
                     </div>
                     <div class="number"><span>{{ listed|length }}</span>+</div>
                     <h4>Pro<span>perties</span></h4>
                  </div>
                  <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                     <div class="icons">
                        <i class="flaticon-people-1"></i>
                     </div>
                     <div class="number"><span>{{ active_users|length }}</span>+</div>
                     <h4>Active <span>Users</span></h4>
                  </div>
                  <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                     <div class="icons">
                        <i class="flaticon-businessman-paper-of-the-application-for-a-job"></i>
                     </div>
                     <div class="number"><span>{{ jobs|length }}</span>+</div>
                     <h4>Active <span>Jobs</span></h4>
                  </div>
               </div>
               <!-- /.row -->
            </div>
            <!-- /.container -->
         </div>
         <!-- /.funfacts -->
         <!-- =-=-=-=-=-=-= Statistics Counter End =-=-=-=-=-=-= -->
         <!-- =-=-=-=-=-=-= Pricing =-=-=-=-=-=-= -->

         <!-- =-=-=-=-=-=-= Pricing End =-=-=-=-=-=-= -->
         <!-- =-=-=-=-=-=-= App Download Section  =-=-=-=-=-=-= -->

         <!-- =-=-=-=-=-=-= Partners End =-=-=-=-=-=-= -->
         <!-- =-=-=-=-=-=-= FOOTER =-=-=-=-=-=-= -->
         <!-- =-=-=-=-=-=-= FOOTER END =-=-=-=-=-=-= -->
      </div>
{% endblock %}

apps/common/templates/common/available_jobs.html
{% extends 'index.html' %}
{% load static %}
{% block loader %}
{% endblock %}
{% block search %}
{% endblock %}
{% block hero %}
{% endblock %}
{% block content %}
      <div class="small-breadcrumb">
         <div class="container">
            <div class=" breadcrumb-link">
               <ul>
                  <li><a href="{% url 'index' %}">Home</a></li>
                  <li><a href="{% url 'common:profile' user.profile.pk %}">Profile</a></li>
                  <li><a href="{% url 'service:manage_service' user.profile.pk %}">Manage Service</a></li>
                  <li><a class="active" href="#">Available Jobs </a></li>
               </ul>
            </div>
         </div>
      </div>
      <!-- Small Breadcrumb -->
      <!-- =-=-=-=-=-=-= Main Content Area =-=-=-=-=-=-= -->
      <div class="main-content-area clearfix">
         <!-- =-=-=-=-=-=-= Latest Ads =-=-=-=-=-=-= -->
         <section class="section-padding gray">
            <!-- Main Container -->
            <div class="container">
               <!-- Row -->
               <div class="row">
                  <!-- Middle Content Area -->
                  <div class="col-md-4 col-sm-12 col-xs-12 leftbar-stick blog-sidebar">
                     <!-- Sidebar Widgets -->
                     <div class="user-profile">
                        <a href="profile.html">
                           {% if user.profile.photo %}
                           <img src="{{ user.profile.photo.url }}" alt="" class="user-photo"></a>
                           {% else %}
                          <img class="image" alt="img" src="{% static 'images/avatar.jpg' %}">
                          {% endif %}
                        <div class="profile-detail">
                           <h6>{{ user.username }}</h6>
                           <ul class="contact-details">
                              <li>
                                 <i class="fa fa-map-marker"></i> {{ user.profile.address }}
                              </li>
                              <li>
                                 <i class="fa fa-envelope"></i>{{ user.email }}
                              </li>
                              <li>
                                 <i class="fa fa-phone"></i> {{ user.profile.phone_number }}
                              </li>
                               <li>
                                 <i class="fa fa-cc"></i> {{ provider }}
                              </li>
                           </ul>
                        </div>
                        <ul>
                           <li ><a href="{% url 'common:profile' user.profile.pk %}">Profile</a></li>
                           <li><a href="{% url 'service:manage_service' user.profile.pk %}">Manage Service <span class="badge"></span></a></li>
                           <li  class="active"><a href="{% url 'common:available_jobs' user.profile.pk %}">Available Jobs <span class="badge"></span></a></li>
                           <li><a href="/account/logout">Logout</a></li>
                        </ul>
                     </div>
                     <!-- Categories -->
                     <div class="widget">
                        <div class="widget-heading">
                           <h4 class="panel-title"><a>Change Your Plan</a></h4>
                        </div>
                        <div class="widget-content">
                           <select class=" form-control">
                              <option label="Select Option"></option>
                              <option value="0">Free</option>
                              <option value="1">Premium</option>
                              <option value="2">Featured</option>
                           </select>
                        </div>
                     </div>
                  </div>
                  <div class="col-md-8 col-sm-12 col-xs-12">
                     <!-- Row -->
                     <div class="row">
                        <!-- Sorting Filters -->
                        <div class="col-md-12 col-xs-12 col-sm-12 col-lg-12">
                           <!-- Sorting Filters Breadcrumb -->
                           <!-- Sorting Filters Breadcrumb End -->
                        </div>
                        <!-- Sorting Filters End-->
                        <div class="clearfix"></div>
                        <!-- Ads Archive -->
                        <div class="posts-masonry">
                           <!-- Listing Ad Grid -->
                           {% for p in requests %}
                           <div class="col-md-6 col-lg-6 col-sm-6 col-xs-12  ">
                              <a href="#">
                              <div class="white category-grid-box-1 ">
                                 <!-- Image Box -->
                                 <div class="image"> <img alt="requester photo" src="{{ p.requester.photo.url }}" class="img-responsive" style="height:200px"> </div>
                                 <!-- Short Description -->
                                 <div class="short-description-1 " >
                                    <!-- Category Title -->
                                    <div class="category-title"> <span>Job Area: {{ p.type_of_service }}</span> </div>
                                    <div class="category-title"><i class="fa fa-map-marker"></i> {{ p.location }}</div>
                                    <!-- Ad Title -->
                                    <h3>
                                       <a title="" href="single-page-listing.html">{{ p.job_title }}</a>
                                    </h3>
                                    <!-- Location -->
                                    <p class="location">Duration: {{ p.duration}}</p>
                                    <!-- Rating -->
                                    <div class="rating">
                                       <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star-o"></i> <span class="rating-count">(2)</span>

                                    </div>
                                     <!-- Price --><span class="ad-price">Budget: N{{ p.price_from }} to N{{ p.price_to }}</span>
                                 </div>
                                 <!-- Ad Meta Stats -->
                                 <div class="ad-info-1">
                                    <ul class="pull-left">
                                       <li> <i class="fa fa-eye"></i><a href="#">445 Views</a> </li>
                                       <li> <i class="fa fa-clock-o"></i>{{ p.date_created }} </li>
                                    </ul>
                                            <ul class="pull-right">
                                               {% if user.profile == p.requester %}
                                                <li>You Created this request</li>
                                                {% else %}
                                               <li> <a type="button" class="btn btn-warning" href="{% url 'service:request_interest' p.pk %}">Bid Offer</a> </li>
                                                {% endif %}
                                            </ul>
                                 </div>
                              </div>
                              </a>
                           </div>
                           {% endfor %}
                           <!-- Listing Ad Grid -->
                           <!-- Listing Ad Grid -->
                        </div>
                        <!-- Ads Archive End -->
                        <div class="clearfix"></div>
                        <!-- Pagination -->
                        <div class="col-md-12 col-xs-12 col-sm-12">
                        </div>
                        <!-- Pagination End -->
                     </div>
                     <!-- Row End -->
                  </div>
                  <!-- Middle Content Area  End -->
               </div>
               <!-- Row End -->
            </div>
            <!-- Main Container End -->
         </section>
      </div>
{% endblock %}

apps/common/templates/common/initial_setup.html
{% extends 'index.html' %}
{% load static %}
{% block loader %}
{% endblock %}
{% block menu %}
{% endblock menu %}
{% block search %}
{% endblock %}
{% block hero %}
{% endblock %}
{% block content %}
<section class="comming-soon-grid">
         <div class="container">
            <div class="row">
               <div class="col-xs-12 comming-soon">
                  <div class="theme-logo">
                     <a href="{% url 'index' %}"><img src="{% static 'images/easy.jpg' %}" alt=""></a>
                  </div>
                  <div class="count-down">
                     <div id="clock"></div>
                  </div>
                  <div>
                      <h3> Welcome {{ user.username }}</h3>
                      <p>Just one more step for your account to be setup </p>
                      <p><a href="{% url 'common:create_profile' user.pk %}">SetUp</a></p>
                  </div>
               </div>
            </div>
         </div>
      </section>
{% endblock %}
{% block footer %}
{% endblock %}